micronaut:
  application:
    name: sales
  jackson:
    bean-introspection-module: true
datasources:
  default:
    url: jdbc:mysql://localhost:3306/salesdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
datasources.default: {}
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory